### ISSUE TITLE
Add CMake toolchain for libnx

### ISSUE THREAD

**Issue by 200iqdevs** [vbe0201/switchcord#6]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I think it's meaningful to create a CMake toolchain file which contains most parts of the main `CMakeLists.txt` file to separate toolchain setup from actual CMake project logic.

**Describe alternatives you've considered**
Well, there aren't really alternatives. Some separate toolchain file would be very nice, but isn't required.

**Additional context**
See: https://cmake.org/cmake/help/v3.7/manual/cmake-toolchains.7.html

**Comment by vbe0201** [comment]
Thanks for your suggestion. I'm working on it!

**Comment by vbe0201** [comment]
Gotcha!
